---
abstract: 'print debug info about ops'
author:
  - 'Malcolm Beattie <retired>, Reini Urban <rurban@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 8.3004, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: B-Debug
no_index:
  directory:
    - t
    - inc
recommends:
  B::Flags: '0.04'
requires:
  B: '0'
  Test::More: '0'
  deprecate: '0.03'
version: '1.26'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
